hotelwatcher/config/routes.rb
Hotelwatcher::Application.routes.draw do
  devise_for :users

  #match 'rooms' => 'rooms#create', :as => :create, :via => :post

  resources :hotels do
    resources :rooms
    resources :comments, except: [:show]
    resources :watches, except: [:show]
  end

  root to: "home#index"
end

hotelwatcher/app/models/hotel.rb
class Hotel < ActiveRecord::Base
  attr_accessible :location_code, :name

  has_many :rooms
  has_many :comments, as: :commentable
  has_many :pictures, as: :imageable

  has_many :taggings, as: :taggable
  has_many :tags, through: :taggings
  
  has_many :watches, as: :watchable
  has_many :watchers, through: :watches, source: :user

  # def add_tag tag_name

  #   if (id.nil? == true)
  #     puts "ID is null, create one first!"
  #   end

  #   tag = Tag.where('lowered_name = ?', tag_name.downcase)
  #   if (tag.nil? == true)
  #     # create a new tag
  #     tag = Tag.new({name: tag_name, lowered_name: tag_name.downcase})
  #     tag.save
  #   end

  #   taggable = Tagging.new({ taggable_type: 'Hotel', taggable_id: id, tag_id: tag.id })
  #   taggable.save
  # end
end

hotelwatcher/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

	before_filter :authenticate_user!

	# list all available hotels
	
	def index
		@hotels = Hotel.includes(:tags)
	end

	# show hotel information - should contain room and price
	
	def show 
		@hotel = get_hotel
	end

	# create new hotel

	def new		
		@hotel = Hotel.new
	end

	def create
		@hotel = Hotel.new(params[:hotel])
		if @hotel.save
			redirect_to(hotels_path)
		else
			render :new 
		end
	end

	# udpate hotel

	def edit
		@hotel = get_hotel
	end

	def update
		@hotel = get_hotel
		if @hotel.update_attributes(params[:hotel])
			redirect_to hotel_path
		else
			render :edit
		end
	end

	# destroy hotel

	def destroy
		@hotel = get_hotel
		flash[:notice] = "Hotel could not be deleted" unless @hotel.destroy
		redirect_to hotels_path
	end

	private 

	def get_hotel
		Hotel.find(params[:id])
	end
end

hotelwatcher/app/views/hotels/_form.html.erb
<h1><%= @hotel.new_record? ? "New Hotel" : "Edit Hotel" %></h1>
<div>
  <%= form_for @hotel, html: { class: 'form-horizontal' } do |f| %>
  <%#= render 'shared/error_messages', target: @hotel %>
  <div class='control-group'>
    <%= f.label :name, class: 'control-label' %>
    <div class='controls'>
      <%= f.text_field :name, class: 'input-xxlarge', size: '10x10' %>
    </div>
  </div>
  <div class='control-group'>
    <%= f.label :location_code, class: 'control-label' %>
    <div class='controls'>
      <%= f.text_field :location_code, class: 'input-xxlarge' %>
    </div>
  </div>
  <% if @hotel.new_record? == false %>
  <div class='control-group'>
    <div class='controls'>
      <table class='table table-striped table-bordered table-condensed'>
        <thead>
          <tr>
            <th>Bed Type</th>
            <th>Total Rooms</th>
            <th>Available Rooms</th>
            <th>Normal Rate</th>
            <th>Current Rate</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @hotel.rooms.each do |room| %>
          <tr>
            <td class='left'><%= room.bed_type %></td>
            <td class='right'><%= room.total_rooms %></td>
            <td class='right'><%= room.available_rooms %></td>
            <td class='right'><%= room.normal_rate %></td>
            <td class='right'><%= room.current_rate %></td>
            <td class='center'>
              <%= link_to "", edit_hotel_room_path(@hotel, room), class: 'icon-edit' %>
              <%= link_to "", hotel_room_path(@hotel, room), class: 'icon-trash', method: :delete %>
            </td>
          </tr>      
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td colspan='5'></td>
            <td><%= link_to "Add New Room", new_hotel_room_path(@hotel.id), class: 'btn btn-small btn-inverse' %></td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
  <% end %>
  <div class='form-actions'>
    <%= f.submit @hotel.new_record? ? "Create Hotel" : "Update Hotel", class: 'btn btn-success' %>
  </div>
  <% end %>
</div>

hotelwatcher/app/views/hotels/_hotel.html.erb
<%= content_tag_for :div, hotel, class: 'row-fluid hotel-item' do %>
  <img src='' alt='no image at the moment' />
  <%= link_to hotel.name, hotel, class: 'title' %>
  <br/>
  <span>
    <%= pluralize hotel.rooms_count, "room type" %> | 
    <!-- <%#= pluralize hotel.pictures_count, "picture" %> | -->
    <%= pluralize hotel.comments_count, "comment" %>
  </span>
  <br/>
  <br/>
  <%= link_to "", edit_hotel_path(hotel), class: 'icon-edit' %> 
  <%= link_to "", hotel_path(hotel), method: :delete, data: { confirm: "Are you sure?" }, class: 'icon-trash' %>
<% end %>

hotelwatcher/app/views/hotels/edit.html.erb
<%= render 'form' %>

hotelwatcher/app/views/hotels/index.html.erb
<!-- <h4>List all hotels here <%#= @hotels.count %></h4> -->
<div class='clearfix' style='padding-top: 30px;'>
  <%= link_to new_hotel_path, class: 'pull-right btn btn-success' do %>
  <i class='icon-plus icon-white'></i> New Hotel
  <% end %>
</div>
<div class='clearfix'>
  <%= render @hotels %>
</div>

hotelwatcher/app/views/hotels/new.html.erb
<%= render 'form' %>

hotelwatcher/app/views/hotels/show.html.erb
<div class='watchbox'>
  <%= watch_button_for @hotel %><br/><br/><span class='pull-right'><%= pluralize @hotel.watchers_count, "watch" %></span>
</div>
<h1><%= @hotel.name %> <%= link_to "", edit_hotel_path, class: 'icon-edit' %></h1>
<h4><%= @hotel.location_code %></h4>
<div>
  <% @hotel.taggings.each do |t| %>
  <%= t.tag.name %>
  <% end %>
</div>
<div id='roomsbox'>
  <%= render 'rooms/room' %>
  </div>
<div id='commentbox'>
  <%= render @hotel.comments, commentable: @hotel %>
  <%= render_comment_form_for @hotel %>
  <%#= render 'shared/register' unless current_user %>
</div>